/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/AddButton.vue')['default']
    GoToTop: typeof import('./src/components/GoToTop.vue')['default']
    JSONTable: typeof import('./src/components/JSONTable.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TableItem: typeof import('./src/components/TableItem.vue')['default']
  }
}
